#!/bin/sh

#### UNIX Script Documentation Block
#
# Script Name:  JHYSPLIT_POST_WEB_RSMC
# RFC Contact:	Binyu Wang, EMC
# Author:	Barbara Stunder, NOAA OAR Air Resources Laboratory
# Abstract:     This is the main driver script for the HYSPLIT RSMC dissemination 
#               to set the processing variables.  This job disseminates the RSMC       
#               (Regional Specialized Meteorological Center (radiological) output
#               to the web.  This is run following the SDM running 
#               setup_hysplit_post_web_rsmc in which the particular file set for
#               dissemination or the sending of "unavailables" is chosen.  
#
# Script History Log:
#  2011        - created
#
# Usage:       
#
#  Script Parameters:
#
#  Modules and Files referenced:
#
#    scripts: exhysplit_post_web_rsmc.sh
#
#    parms:          
#
#    fix: graph_snd2forgn.names              
#
#    executables:       
#
#    input file: $COMSTAMP/ondemand_hysplit.stamp
#
#    other: 
#
# Condition codes:
#
# User controllable options:
#
# Attributes:
#     Language:  AIX UNIX
#     Machine:   NCEP CCS
#
####
set -xa
export PS4='$SECONDS + '
date

####################################
# Specify NET and RUN
####################################
export NET=${NET:-hysplit}
export RUN=${RUN:-hysplit}
# #### 04/11/2011 ######################################
# SETUP HYSPLIT RSMC POST-PROCESSING VARIABLES to send to web
# ######################################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$

# PATH for working directory
export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
mkdir -m 775 -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# SENDECF  - Flag Events on ECF 
# SENDCOM  - Copy Files From TMPDIR to $com 
####################################
export SENDWEB=${SENDWEB:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEhysplit=${HOMEhysplit:-/lfs/h1/ops/${envir}/packages/${NET}.${hysplit_ver}}
export EXEChysplit=${EXEChysplit:-$HOMEhysplit/exec}
export FIXhysplit=${FIXhysplit:-$HOMEhysplit/fix}

msg="JOB $job HAS BEGUN"
postmsg "$msg"

###############################################
## Run setpdy and initialize PDY variables
###############################################
export COMSTAMP=${COMSTAMP:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/timestamps}
export cyc=`cat $COMSTAMP/ondemand_hysplit.stamp | cut -c9-10`
export PDY=`cat $COMSTAMP/ondemand_hysplit.stamp | cut -c1-8`

export cycle=t${cyc}z

setpdy.sh
. PDY

#######################################################
#/usr/bin/rsync -tv -e ssh  ${FILE} ${RZDM_USR}@${MACHINE_RZDM}:${RZDM_DIR}/${FILE}
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${RUN}.${PDY}}
export GESIN=${GESIN:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/input}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${RUN}.${PDY}}

export COMOUTRUS=${COMOUTRUS:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/restrict/US}
export COMOUTRJNT=${COMOUTRJNT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/restrict/JNT_STMT}
mkdir -m 775 -p $COMOUT $COMOUTRUS $COMOUTRJNT

[[ -d "${COMOUT}" ]] || mkdir -m 775 -p "${COMOUT}"
[[ -d "${COMOUTUS}" ]] || mkdir -m 775 -p "${COMOUTUS}"
[[ -d "${COMOUTJNT}" ]] || mkdir -m 775 -p "${COMOUTJNT}"

env

#############################################################
# Execute the script
#############################################################
${HOMEhysplit}/scripts/exhysplit_ondemand_rsmc_web.sh
## Currently "to NCEP RSMC web" is not officially an operational pathway
## so it can not be allowed to fail during operational runs
## export err=$?; err_chk
export err=$?

if [ -s $pgmout ]; then
  cat $pgmout
fi
msg="$job completed normally"
postmsg "$msg"

##################################################
# Remove the Temporary working directory
##################################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date -u
