#!/bin/ksh

#### UNIX Script Documentation Block
#
# Script Name:  JHYSPLIT_WAFS
# RFC Contact:	Binyu Wang, EMC
# Author:	Barbara Stunder, NOAA OAR Air Resources Laboratory
# Abstract:     This is the main driver script for the HYSPLIT WAFS to set the
#               processing variables.  This job disseminates the volcanic ash output
#               to the public, initially over the WAFS circuit.  This is run following 
#               the SDM running setup_hysplit_wafs in which the particular file for
#               dissemination is chosen.  
#
# Script History Log:
# 04-04-03 frost - change ghostscript to 7.05 from 5.10
# 04-01-09 SENDPCOM
# 04-24-09 SDM_PRNTR
#
# Usage:       
#
#  Script Parameters:
#
#  Modules and Files referenced:
#
#    scripts: exhysplit_wafs.sh
#
#    parms:          
#
#    fix: graph_snd2forgn.names              
#
#    executables:       
#
#    input file: $COMSTAMP/ondemand_hysplit.stamp
#
#    other: 
#
# Condition codes:
#
# User controllable options:
#
# Attributes:
#     Language:  Linux    
#     Machine:   NCEP WCOSS
#
####
export PS4='$SECONDS + '
date
set -xa
####################################
# Specify NET and RUN
####################################
export NET=${NET:-hysplit}
export RUN=${RUN:-hysplit}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$

# PATH for working directory
export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
mkdir -m 775 -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $com 
####################################
export SENDPCOM=${SENDPCOM:-YES} # ARL added SENDPCOM test to exhysplit_wafs.sh
export SENDCOM=${SENDCOM:-YES}
export SENDPRINT=${SENDPRINT:-YES} 		# YES to print at the SDM printer or coop printer

####################################
# Specify Execution Areas
####################################
export HOMEhysplit=${HOMEhysplit:-/lfs/h1/ops/${envir}/packages/${NET}.${hysplit_ver}}
export EXEChysplit=${EXEChysplit:-$HOMEhysplit/exec}
export FIXhysplit=${FIXhysplit:-$HOMEhysplit/fix}
export USHhysplit=${USHhysplit:-$HOMEhysplit/ush}
export GESIN=${GESIN:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/input}

##############################
# Set up the UTILITIES
##############################

msg="JOB $job HAS BEGUN"
postmsg "$msg"

export COMSTAMP=${COMSTAMP:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/timestamps}
export cyc=`cat $COMSTAMP/ondemand_hysplit.stamp | cut -c9-10`
export PDY=`cat $COMSTAMP/ondemand_hysplit.stamp | cut -c1-8`

export cycle=t${cyc}z

##############################################
# Run setpdy and initialize PDY variables
##############################################
setpdy.sh
. PDY

######################################################

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${RUN}.${PDY}}
export pcom=${pcom:-${COMOUT}/wmo}

mkdir -m 775 -p $COMOUT $pcom

#export GS_LIB=${GS_LIB:-/usr/share/fonts}

env

#############################################################
# Execute the script
#############################################################
${HOMEhysplit}/scripts/exhysplit_ondemand_volc_wafs.sh
export err=$?; err_chk

if [ -s $pgmout ]; then
  cat $pgmout
fi

msg="$job completed normally"
postmsg "$msg"

##################################################
# Remove the Temporary working directory
##################################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date -u
