#!/bin/ksh

set -xa
export PS4='$SECONDS + '						
date -u	

# #### 11/10/25 #######################################
# set hysplit processing variables for the first 6 hours of 
# forecast output from the previous 4 HYSPLIT-RRFS cycles
# and concatenate them.
# Modules and Files referenced:
# scripts: scripts/exhysplit_prep_archive.sh
#
# Nov 2025 (BYW)- Created from JHYSPLIT_PREP_RRFS
# #####################################################

# Setup directories and common environment variable
export model=${model:-hysplit}
export RUN=${RUN:-hysplit}
export NET=${NET:-hysplit}

####################################
# Forecast details - RRFS
####################################
export FHR_START=${FHR_START:-0}	# start forecast hour 
#export FHR_MAX=${FHR_MAX:-48}          # (18) max forecast hour # 0 to not create forecast
export FHR_INT=1	# forecast hour interval
export CYC_INT="06"     # cycle interval (hours) (changes needed in exhysplit_prep.sh for CYC_INT=1)
export mdl=rrfs
export mdl_ver=${rrfs_ver}
export jname9=rrfs
export prefix=${prefix:-rrfs}
export MDL=RRFS
export fname=${fname:-prslev.12km}  #  predefined in ecf script
export cycles_back=${cycles_back:-4}   ## Number of cycles to process
########################################################## 
# obtain unique process id (pid) and make temp directory
########################################################## 
export pid=$$

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

ecfrid=$(echo ${PBS_JOBID} | awk -F"." '{print $1}')
export job=${job:-${PBS_JOBNAME}}
export jobid=${jobid:-${PBS_JOBNAME}.${ecfrid}}

export LSB_OUTPUTFILE=${LSB_OUTPUTFILE:-${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${ecfrid}}
# PATH for working directory
export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
export KEEPDATA=${KEEPDATA:-NO}
mkdir -m 775 -p ${DATA}
cd ${DATA}

########################################################## 

export cycle=${cycle:-t${cyc}z}

####################################
# SENDECF  - Flag Events on ECF 
# SENDCOM  - Copy Files From TMPDIR to $com 
# SENDDBN  - 
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# parallel vars
####################################
export TASKS=${TASKS:-${NCPUS}}
export MPMD=on
export MP_LABELIO=YES

####################################
# Specify Execution Areas
####################################
export HOMEhysplit=${HOMEhysplit:-/lfs/h1/ops/${envir}/packages/${NET}.${hysplit_ver}}
export EXEChysplit=${EXEChysplit:-$HOMEhysplit/exec}
export JOBShysplit=${JOBShysplit:-$HOMEhysplit/jobs}              
export USHhysplit=${USHhysplit:-$HOMEhysplit/ush}

msg="JOB ${job} HAS BEGUN"
echo ${msg}

##############################################
# Run setpdy and initialize PDY variables
##############################################
setpdy.sh
. PDY

####################################
# Set Directories Where Model Input is Located
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${NET}.${PDY}}
mkdir -m 775 -p ${COMOUT}
export COMOUT_HYSPT=$COMOUT
 
env

########################################################
# Execute the script.
#######################################################
${HOMEhysplit}/scripts/exhysplit_prep_rrfs_arc.sh
export err=$?; err_chk

echo "Hysplit Prep ${MDL}${mdlcomsfx} Completed Normally."

if [ -s ${pgmout} ]; then
  cat ${pgmout}
fi

msg="${job} completed normally"
echo ${msg}

##################################################
# Remove the Temporary working directory
##################################################
if [ "${KEEPDATA}" != "YES" ] ; then
  cd ${DATAROOT}
  rm -rf ${DATA}
fi

date -u
