#!/bin/ksh

set -xa
export PS4='$SECONDS + '						
date -u	

# #### 07/11/03 #######################################
#
#       JHYSPLIT_HRRR_PREP
#
# SET HYSPLIT PROCESSING VARIABLES FOR AQM12K
#  NOTE that there are only a few changes between the 
#       hysplit preprocessors (nam, aqm, gfsonedeg, namak and nam(egrd3d))
# 11-02-2005 Created from JHYSPLIT_NAM12K_PREP
# 05-30-2006 Generalized version, see Forecast/Archive details section
# 07-28-2006 ... for nam (nam...awphys...)
# 2008 April ... to NCEP
# 2011 Sept 07 from RUC to RAP
# 2017 April 21 - HRRR
# #####################################################

####################################
# Specify NET Name and model
#
# model - model grib field to repack
####################################
export NET=${NET:-hysplit}
export model=${model:-hysplit}
export RUN=${RUN:-hysplit}

####################################
# Forecast/Archive details - nam12k
####################################
export FHR_START=${FHR_START:-0}	# start forecast hour 
export FHR_MAX=${FHR_MAX:-18}      # (18) # max forecast hour # 0 to not create forecast
export FHR_INT=1	# forecast hour interval
export CYC_INT="01"     # cycle interval (hours) (changes needed in exhysplit_prep.sh_serial.ecf for CYC_INT=1)
export LEN_ARC=${LEN_ARC:-0}        # (1) length of archive (days)
 # NOTE: my non-poe job gives 23-h A file correctly
 #       but ops poe job is only an 11-h file because it's 4 tasks
export mdl=hrrr
export mdl_ver=${hrrr_ver}
export mdl2=        	# for sref
export mem=  		# sref member
export mdlcom=${mdl}
export mdlcomsfx=".grib2" 
export mdlday=${mdl}
export jname9=hrrr
export domain=null
export prefix=${mdl}
export MDL=HRRR
export fname=wrfnatf
export sfx=
export convert="hrrr2arl"  	# program to convert to HYSPLIT (ARL) format
export dashi="-i"
                        #        nam, null
export dashg=     	# grid, gfs defaults to g3=global
                        #       wrf defaults to aqm
                        #       nam, null
export dashp=    	# precipitation, 
                        #    wrf default is difference, else previous
                        #      because of 3-h accum for 06z and 18z cycles
                        #      but 12-h precip accumulation for 00z and 12z
                        #    nam,gfs, null
export dashs=           # supplemental grib file, optional for wrf; others null
export dashv=     	#vertical resolution,
                        #    wrf, default to cmaq (2=<700mb, 3=full)
                        #    others, null
export dashx=           #extract
                        #    wrf, default to 3-d, 2 for 2-d only
                        #    others, null
export dashz=     	# initialization flag,
                        #    gfs (z0=do not initialize)
                        #    others, null
export loop=1     	# per hypslit_prep_arch.sh 
                        #    wrf, 0
                        #    others, 1

########################################################## 
# obtain unique process id (pid) and make temp directory
########################################################## 
export pid=$$

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

ecfrid=$(echo ${PBS_JOBID} | awk -F"." '{print $1}')
export job=${job:-${PBS_JOBNAME}}
export jobid=${jobid:-${PBS_JOBNAME}.${ecfrid}}

export LSB_OUTPUTFILE=${LSB_OUTPUTFILE:-${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${ecfrid}}
# PATH for working directory
export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
export KEEPDATA=${KEEPDATA:-NO}
mkdir -m 775 -p ${DATA}
cd ${DATA}

########################################################## 

export cycle=${cycle:-t${cyc}z}

####################################
# SENDECF  - Flag Events on ECF 
# SENDCOM  - Copy Files From TMPDIR to $com 
# SENDDBN  - 
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# parallel vars
####################################
export TASKS=${TASKS:-${NCPUS}}
export MPMD=on
export MP_LABELIO=YES

####################################
# Specify Execution Areas
####################################
export HOMEhysplit=${HOMEhysplit:-/lfs/h1/ops/${envir}/packages/${NET}.${hysplit_ver}}
export EXEChysplit=${EXEChysplit:-${HOMEhysplit}/exec}
export USHhysplit=${USHhysplit:-${HOMEhysplit}/ush}

msg="JOB ${job} HAS BEGUN"
echo ${msg}

##############################################
# Run setpdy and initialize PDY variables
##############################################
setpdy.sh
. PDY

####################################
# Set Directories Where Model Input is Located
####################################
export COMIN=${COMIN:-$(compath.py ${NET}/${hysplit_ver})/${NET}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${NET}.${PDY}}
mkdir -m 775 -p ${COMOUT}
export COMMDLIN=${COMMDLIN:-$(compath.py ${envir}/com/${mdl}/${mdl_ver})}
export COMOUT_HYSPT=${COMOUT_HYSPT:-$(compath.py ${envir}/com/${NET}/${hysplit_ver})/${NET}.${PDY}}
 
env

########################################################
# Execute the script.
#######################################################
${HOMEhysplit}/scripts/exhysplit_prep.sh
export err=$?; err_chk

echo "Hysplit Prep ${MDL}${mdlcomsfx} Completed Normally."

if [ -s ${pgmout} ]; then
  cat ${pgmout}
fi

msg="${job} completed normally"
echo ${msg}

##################################################
# Remove the Temporary working directory
##################################################
if [ "${KEEPDATA}" != "YES" ] ; then
  cd ${DATAROOT}
  rm -rf ${DATA}
fi

date -u
